services:
  mongo.backcat:
    image: mongo:6
    restart: always
    env_file:
      - ./src/.env
    container_name: mongo.backcat

    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_DB}

    ports:
      - ${MONGO_PORT}:27017

    healthcheck:
      test: ["CMD", 'db.runCommand("ping").ok', mongosh, "localhost:27017/${MONGO_DB}", --quiet]
      interval: 10s
      timeout: 10s
      retries: 5

    volumes:
      - mongo.backcat:/data/db

volumes:
  mongo.backcat:
