#Пользователь по email
GEt http://localhost:3014/api/users/user@yandex.com HTTP/1.1

###

#Пользователь по ID
GEt http://localhost:3014/api/users/67645530e791c623065e30c1 HTTP/1.1

###


#Проверка аутентификации
POST http://localhost:3014/api/auth/check HTTP/1.1

###


#Создание нового пользователя

POST http://localhost:3014/api/auth/register HTTP/1.1
Content-Type: application/json

{
  "email":"oleg2@yandex.com",
  "name":"Oleg",
  "password":"123456"
}

###


#Авторизация пользователя по email и password
POST http://localhost:3014/api/auth/login HTTP/1.1
Content-Type: application/json

{
  "email":"oleg@yandex.com",
  "password":"123456"
}
###

#Получение информации о пользователе по ID
GET http://localhost:3014/api/auth/user/680e0c94d4bdf2a3c9abc872 HTTP/1.1

###


#Смена пароля пользователя
PUT http://localhost:3014/api/auth/change-password HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Nzk2MDg5MDNiY2UyZWY5ZmY5MTdmY2UiLCJlbWFpbCI6Im9sZWdAeWFuZGV4LmNvbSIsIm5hbWUiOiJPbGVnIiwiY3JlYXRlQXQiOiIyMDI1LTAxLTI2VDEwOjAzOjU5LjMxNFoiLCJpYXQiOjE3MzgyMjg3MjAsImV4cCI6MTczODIyOTAyMH0.Ru7x2c0kyK_9N-xcnAyPyoqBwS85ofQxnm64F_qaF5I
Content-Type: application/json

{
  "oldPassword":"123456",
  "newPassword":"123456",
  "id": "679608903bce2ef9ff917fce"
}
###

#Поиск пользователя по email
GEt http://localhost:3014/api/users/oleg@yandex.com HTTP/1.1
###

#Поиск пользователя по ID
GEt http://localhost:3014/api/auth/user/67960a2f6be01eeb755fc5f8 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzY0NTUzMGU3OTFjNjIzMDY1ZTMwYzEiLCJlbWFpbCI6InVzZXJAeWFuZGV4LmNvbSIsIm5hbWUiOiJPbGVnIiwiY3JlYXRlQXQiOiIyMDI0LTEyLTE5VDE3OjE3OjM1LjE5NloiLCJpYXQiOjE3Mzc4MzQ2MDMsImV4cCI6MTczNzgzNDkwM30.-Aq21w4LsW3PT5rhcd1967oxWUPWe1hwM9KXVvMoFsM
###

#Avatar по ID
PUT http://localhost:3001/api/auth/avatar/67645530e791c623065e30c1 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzY0NTUzMGU3OTFjNjIzMDY1ZTMwYzEiLCJlbWFpbCI6InVzZXJAeWFuZGV4LmNvbSIsIm5hbWUiOiJPbGVnIiwiY3JlYXRlQXQiOiIyMDI0LTEyLTE5VDE3OjE3OjM1LjE5NloiLCJpYXQiOjE3Mzc4MzQ2MDMsImV4cCI6MTczNzgzNDkwM30.-Aq21w4LsW3PT5rhcd1967oxWUPWe1hwM9KXVvMoFsM
Content-Type: application/json

{
  "avatarId":"user.jpg"
}
###


POST http://localhost:3001/api/auth/refresh HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzY0NTUzMGU3OTFjNjIzMDY1ZTMwYzEiLCJlbWFpbCI6InVzZXJAeWFuZGV4LmNvbSIsIm5hbWUiOiJPbGVnIiwiY3JlYXRlQXQiOiIyMDI0LTEyLTE5VDE3OjE3OjM1LjE5NloiLCJpYXQiOjE3Mzc4MzQ2MDMsImV4cCI6MTczNzgzNDkwM30.-Aq21w4LsW3PT5rhcd1967oxWUPWe1hwM9KXVvMoFsM
###

# Подписка на другого пользователя
PUT http://localhost:3001/api/auth/subscribe/67960a2f6be01eeb755fc5f8 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Nzk2MDg5MDNiY2UyZWY5ZmY5MTdmY2UiLCJlbWFpbCI6Im9sZWdAeWFuZGV4LmNvbSIsIm5hbWUiOiJPbGVnIiwiY3JlYXRlQXQiOiIyMDI1LTAxLTI2VDEwOjAzOjU5LjMxNFoiLCJpYXQiOjE3Mzc4ODc4NTMsImV4cCI6MTczNzg4ODE1M30.ebN7EYFVsC3eS5peyIvn9CI7oNK78snY8HzM3H6fj3g
###

# Отпиписка от другого пользователя
PUT http://localhost:3001/api/auth/unsubscribe/67960a2f6be01eeb755fc5f8 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2Nzk2MDg5MDNiY2UyZWY5ZmY5MTdmY2UiLCJlbWFpbCI6Im9sZWdAeWFuZGV4LmNvbSIsIm5hbWUiOiJPbGVnIiwiY3JlYXRlQXQiOiIyMDI1LTAxLTI2VDEwOjAzOjU5LjMxNFoiLCJpYXQiOjE3Mzc4ODc4NTMsImV4cCI6MTczNzg4ODE1M30.ebN7EYFVsC3eS5peyIvn9CI7oNK78snY8HzM3H6fj3g
###

# Demo route for Pipe
GET http://localhost:3001/api/auth/demo/677e6e3a81fa724ae26b3c91 HTTP/1.1.
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI2NzY0NTUzMGU3OTFjNjIzMDY1ZTMwYzEiLCJlbWFpbCI6InVzZXJAeWFuZGV4LmNvbSIsIm5hbWUiOiJPbGVnIiwiY3JlYXRlQXQiOiIyMDI0LTEyLTE5VDE3OjE3OjM1LjE5NloiLCJpYXQiOjE3Mzc4MzQ2MDMsImV4cCI6MTczNzgzNDkwM30.-Aq21w4LsW3PT5rhcd1967oxWUPWe1hwM9KXVvMoFsM
###



